[2025-01-24T06:38:36.890+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T06:38:36.895+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T06:38:36.897+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T06:38:36.897+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T06:38:36.902+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2025-01-23 00:00:00+00:00
[2025-01-24T06:38:36.904+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T06:38:36.905+0000] {standard_task_runner.py:72} INFO - Started process 90 to run task
[2025-01-24T06:38:36.905+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/GCP Project/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmptqwpzvh2']
[2025-01-24T06:38:36.906+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask local_to_gcs_task
[2025-01-24T06:38:36.923+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2025-01-23T00:00:00+00:00 [running]> on host 318629d7f412
[2025-01-24T06:38:36.948+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-01-24T06:38:36.948+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T06:38:43.270+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T06:38:43.284+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T06:38:43.285+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250124T063836, end_date=20250124T063843
[2025-01-24T06:38:43.301+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T06:38:43.314+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-24T06:38:43.315+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
