[2025-01-24T08:01:01.889+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T08:01:01.897+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task_yellow_tripdata_2021-03.csv scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T08:01:01.901+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task_yellow_tripdata_2021-03.csv scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T08:01:01.901+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2025-01-24T08:01:01.906+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): format_to_parquet_task_yellow_tripdata_2021-03.csv> on 2025-01-23 00:00:00+00:00
[2025-01-24T08:01:01.909+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T08:01:01.911+0000] {standard_task_runner.py:72} INFO - Started process 64 to run task
[2025-01-24T08:01:01.911+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task_yellow_tripdata_2021-03.csv', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/GCP Project/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_e7ta3dp']
[2025-01-24T08:01:01.913+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask format_to_parquet_task_yellow_tripdata_2021-03.csv
[2025-01-24T08:01:01.976+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task_yellow_tripdata_2021-03.csv scheduled__2025-01-23T00:00:00+00:00 [running]> on host 7526bafc575d
[2025-01-24T08:01:02.029+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='format_to_parquet_task_yellow_tripdata_2021-03.csv' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-01-24T08:01:02.032+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T08:01:02.061+0000] {data_ingestion_gcs_dag.py:61} INFO - 开始读取CSV文件: /opt/***/yellow_tripdata_2021-03.csv
[2025-01-24T08:01:02.070+0000] {data_ingestion_gcs_dag.py:75} ERROR - 转换过程中发生错误: [Errno 2] Failed to open local file '/opt/***/yellow_tripdata_2021-03.csv'. Detail: [errno 2] No such file or directory
[2025-01-24T08:01:02.071+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/GCP Project/data_ingestion_gcs_dag.py", line 63, in format_to_parquet
    table = pv.read_csv(src_file, parse_options=pv.ParseOptions(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_csv.pyx", line 1256, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1115, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 2188, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 2159, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 1245, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 1257, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/yellow_tripdata_2021-03.csv'. Detail: [errno 2] No such file or directory
[2025-01-24T08:01:02.085+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task_yellow_tripdata_2021-03.csv, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250124T080101, end_date=20250124T080102
[2025-01-24T08:01:02.121+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T08:01:02.121+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task format_to_parquet_task_yellow_tripdata_2021-03.csv ([Errno 2] Failed to open local file '/opt/airflow/yellow_tripdata_2021-03.csv'. Detail: [errno 2] No such file or directory; 64)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/GCP Project/data_ingestion_gcs_dag.py", line 63, in format_to_parquet
    table = pv.read_csv(src_file, parse_options=pv.ParseOptions(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_csv.pyx", line 1256, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1115, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 2188, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 2159, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 1245, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 1257, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/yellow_tripdata_2021-03.csv'. Detail: [errno 2] No such file or directory
[2025-01-24T08:01:02.136+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T08:01:02.143+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
